In [ ]:
import numpy as np

## Сортировка данных

### Сортировка по оси:

In [ ]:
a = np.array([[4, 3, 5], [1, 2, 1]])
b = np.sort(a, axis=1)
b

array([[3, 4, 5],
       [1, 1, 2]])

Заметка: Сортирует каждую строку отдельно!

### Сортировка на месте:

In [ ]:
a.sort(axis=1)
a

array([[3, 4, 5],
       [1, 1, 2]])

### Сортировка с причудливой индексацией:

In [ ]:
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
j

array([2, 3, 1, 0])

In [ ]:
a[j]

array([1, 2, 3, 4])

### Нахождение минимума и максимума:

In [ ]:
a = np.array([4, 3, 1, 2])
j_max = np.argmax(a)
j_min = np.argmin(a)
j_max, j_min

(0, 2)