In [ ]:
import numpy as np

## Базовые сокращения

### Вычисление суммы

In [ ]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [ ]:
x.sum()

10

Сумма по столбцам и строкам

In [ ]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [ ]:
x.sum(axis=0)       # столбцы (первое измерение)

array([3, 3])

In [ ]:
x[:, 0].sum(), x[:,1].sum()

(3, 3)

In [ ]:
x.sum(axis=1)     # строки (второе измерение)

array([2, 4])

In [ ]:
x[0, :].sum(), x[1, :].sum()

(2, 4)

То же самое, но с более высокими измерениями

In [ ]:
x = np.random.rand(2, 2, 2)
x.sum(axis=2)[0,1]

1.1919962163112028

In [ ]:
x[0, 1, :].sum()

1.1919962163112028

### Другие сокращения

Экстремумы:

In [ ]:
x = np.array([1, 3, 2])
x.min()

1

In [ ]:
x.max()

3

In [ ]:
x.argmin()      # индекс минимума

0

In [ ]:
x.argmax()      # инлекс максимума

1

Логические операции:

In [ ]:
np.all([True, True, False])

False

In [ ]:
np.any([True, True, False])

True

**Заметка:** Могут быть использованы для сравнения массивов:

In [ ]:
a = np.zeros((100, 100))
np.any(a != 0)

False

In [ ]:
np.all(a == a)

True

In [ ]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
( (a <= b) & (b <= c) ).all()

True

Статистика:

In [ ]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [ ]:
np.median(x)

1.5

In [ ]:
np.median(y, axis=-1)     # последняя ось

array([2., 5.])

In [ ]:
x.std()     # стандартное отклонение генеральной совокупности

0.82915619758885

... и много чего ещё (лучше учиться на ходу)